services:
  db:
    container_name: wfm-db
    image: postgres:17.2
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./api/.env
  api:
    container_name: wfm-api
    build:
      context: api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: rowegie@wfm.com
      PGADMIN_DEFAULT_PASSWORD: rowegie
    volumes:
      - ./pg-admin/:/var/lib/pgadmin
